
[functions.publish_room_event]
enabled = true
verify_jwt = true
import_map = "./functions/publish_room_event/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/publish_room_event/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/publish_room_event/*.html" ]
